services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SENHA123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - minha-rede
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Senha123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 2

  microservico:
    build:
      context: ./LojaEmpacotamentoApi
      dockerfile: Dockerfile
    container_name: microservico-loja-empacotamento-api
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    networks:
      - minha-rede

volumes:
  sqlvolume:

networks:
  minha-rede:
